### ISSUE TITLE
App started, but error thrown

### ISSUE THREAD

**Issue by phuongnd08** [vasily-v-ryabov/pywinauto-64#23]
I'm trying to start the app with this:
```
from pywinauto import application
app = application.Application()
app.start_("C:\path\to\app.exe")
```

In the UI, I can see the app is running. But pywinauto is raising this:
```
    raise AppStartError("WaitForInputIdle: " + str(ctypes.WinError()))
pywinauto.application.AppStartError: WaitForInputIdle: [Error 2] The system cannot find the file specified.
```

**Comment by vasily-v-ryabov** [comment]
Does your app path contain non-English characters? If yes, please try English-only path name. Let me know whether it works or not.

**Comment by phuongnd08** [comment]
No it's not. But it contains spaces (since it's in "Program Files (x86)" folder)

**Comment by vasily-v-ryabov** [comment]
Spaces shoudn't matter here. Do you use `r` specifier before the string? or double back slashes `\\`?

**Comment by phuongnd08** [comment]
I use this: `app.start_("C:\Program Files (x86)\My App\My App.exe")`

Upon closer inspection, I think when the app run, it actually invoke a new process (same file.exe) but with different commands. Perhaps it's the reason. Could pywinauto track it?

**Comment by vasily-v-ryabov** [comment]
That's interesting case. I would say no. But you can connect to new process using `app.connect_(path='app.exe')` or `app.connect_(title='Main window title')`.

**Comment by phuongnd08** [comment]
Thanks. `.connect_` works like a charm :D

**Comment by phuongnd08** [comment]
Question, I can get the window after `app.connect_` with: `app.window_(title_re="someregex")` which return a `pywinauto.application.ActionDialog` but this doesn't has `print_control_identifiers` nor `PrintControlIdentifiers`. How can I get a button with text `"Button1"` inside it?

**Comment by vasily-v-ryabov** [comment]
Call like `app.Window_(**criteria).PrintControlIdentifiers()` works because it's really equivalent to `app.Window_(**criteria).WrapperObject().PrintControlIdentifiers()`. So you can use `WrapperObject()` for debug purposes to get concrete wrapper instead of WindowSpecification object which can belong to even non-existing control. WindowSpecification is just criteria description for search. But it contains overridden method `__getattr__` which hides `WrapperObject()` call to make your code more compact. This is a power of Python. :)
