### ISSUE TITLE
Encoding issue in method Texts() - WordPad.exe test case (Python 2.x only)

### ISSUE THREAD

**Issue by vasily-v-ryabov** [vasily-v-ryabov/pywinauto-64#4]
This encoding issue is reproduced in Python 2.x only (Python 3.4 works fine). Example code to reproduce:

    from __future__ import print_function
    import pywinauto
    
    app = pywinauto.Application().start_(r"c:\Program Files\Windows NT\Accessories\wordpad.exe")
    app.DocumentWordPad.UIRibbonDockTop.ClickInput(coords=(580, 60))
    
    list = app.DateAndTime.ListBox.WrapperObject()
    
    columns = list.Texts()
    print(columns)

See _get_multiple_text_items() function where `text = ctypes.create_unicode_buffer(text_len + 1)` is called and then used for text extraction.

**Comment by airelil** [comment]
How about the next fix:
```
import sys

...

if six.PY3:
        texts.append(text.value.encode(sys.stdout.encoding,'ignore'))
else:
        texts.append(text.value.decode('utf-8','ignore'))
```
Works on Python3.4 and Python2.7 for me.

**Comment by airelil** [comment]
One more update. In fact, the code above produces **bytes** type for the Python3 case. If we want to stick to unicode it should be re-encoded back to UTF-8:
```python
import sys
...
if six.PY3:
        texts.append(text.value.encode(sys.stdout.encoding,'ignore').decode('utf-8','ignore'))
else:
        texts.append(text.value.decode('utf-8','ignore'))
```

**Comment by vasily-v-ryabov** [comment]
Suggested fix doesn't work in Python 2.6:

       texts.append(text.value.decode('utf-8','ignore'))
      File "C:\Python26_x64\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)

**Comment by airelil** [comment]
Moreover, it even doesn't work in Python 2.7. Looks as I was too tired yesterday... I'm checking it out now

**Comment by airelil** [comment]
I figured out why it worked for me yestereday. I didn't update my sources to the latest commit. So with a kind of rolling back some changes we can get something working here:
```python
import sys
...
        if six.PY3:
            text = ctypes.create_unicode_buffer(text_len + 1)
        else:
            text = ctypes.create_string_buffer(text_len + 1)

        wrapper.SendMessage(item_get_msg, i, ctypes.byref(text))

        if six.PY3:
            texts.append(text.value.encode(sys.stdout.encoding,'ignore').decode('utf-8','ignore'))
        else:
            texts.append(text.value.decode('utf-8','ignore'))
```

*_get_multiple_text_items* itself can be slightly optimized:
```python
    # get the text for each item in the combobox
    if six.PY3:
        create_buf = lambda l: ctypes.create_unicode_buffer(l + 1)
        enc = lambda t: t.value.encode(sys.stdout.encoding,'ignore').decode('utf-8','ignore')
    else:
        create_buf = lambda l: ctypes.create_string_buffer(text_len + 1)
        enc = lambda t: t.value.decode('utf-8','ignore')

    for i in range(0, num_items):
        text_len = wrapper.SendMessage (item_len_msg, i, 0)
        text = create_buf(text_len)
        wrapper.SendMessage(item_get_msg, i, ctypes.byref(text))
        texts.append( enc(text))
```

**Comment by airelil** [comment]
@vasily-v-ryabov, I've read tons about encoding/decoding. Still not sure that I fully mastered it but there are several thoughts about *_get_multiple_text_items* and some other things in general: 
 1. The "right" way to handle things is to stick with unicode so it looks as *ctypes.create_unicode_buffer* is a right function here as it returns buffers of c_wchar in Py2 and Py3 as well
 2. I'd prefer to call *win32functions.SendMessage* because it seems like it just does the job passing buffers from/to Win API without any hassle.
 3. Running encode/decode on the *text.value* when building the *texts* list is needless or even can be harmful as some symbols could be stripped during such manipulations while the main goal of the function (as I understand it) is to get contents of all items.
 4. As I learned, a general rule of thumb says: "Decode early; Unicode everywhere; Encode late".  Taking the example of your scenario maybe the list items should be encoded right before printing or even during the printing. 
 5. There is still a big question about choosing encoding. As you saw, using *sys.stdout.encoding* is not reliable way to detect it while applying 'utf-8' produces 'fancy' strings. Maybe *locale.getpreferredencoding()* can make it...

**Comment by vasily-v-ryabov** [comment]
Fixed the issue. Now print(columns) output is:
    ['', u'27.03.2015', u'27.03.15', u'27.3.15', u'27/03/15', u'2015-03-27', u'27 \u043c\u0430\u0440\u0442\u0430 2015 \u0433.', u'16:44:06']
But if you print every list element it has correct encoding. For example, print(columns[6]) output is:
    27 марта 2015 г.
